### ISSUE TITLE
Holding A or B to make text go fast will bypass learning songs

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#225] opened 2022-03-27 03:52 UTC
## Current Behavior

If you hold the A or B button to make text go faster and advancing dialog will make the note box for learning songs go by. Soft-locks when learning child songs, but doesn't soft-lock when learning warp songs.
## Expected Behavior

Should let the NPC play the song, then let you learn the song after them.
## Steps to Reproduce

1. Go anywhere you can learn a song. (Easiest is the warp to Kakariko as Adult in debut save file and go to the windmill for Song of Storms)
2. Hold the A or B button while advancing dialog and it will eventually bypass the song note box

https://user-images.githubusercontent.com/99471756/160265880-89ed1cf5-e131-4a2c-ace7-df9aa6f5abc8.mp4

**Comment by DaMarkov** [comment] 2022-03-27 14:09
Can be reproduced with master quest debug, but not in Project 64

**Comment by DaMarkov** [comment] 2022-03-27 20:33
Seems to be fixed now. I tested it a Kakariko (windmil) with the master quest debug rom.

**Closed** 2022-03-27 22:56 UTC
Labels: Debug ROM
