### ISSUE TITLE
Dim lighting issue in front of caste with sword charge

### ISSUE THREAD

**Issue by frizzle101101** [blawar/ooot#72] opened 2022-02-06 21:14 UTC
So in front of the castle when you charge your sword there is just blackness looks like lighting issue maybe texture issue

**Comment by Zero3K** [comment] 2022-02-06 21:16
Duplicate of #3.

**Closed by Zero3K** 2022-02-06 21:16 UTC

**Comment by frizzle101101** [comment] 2022-02-06 21:17
Word thanks 😅 my bad
