### ISSUE TITLE
Green Background When Paused

### ISSUE THREAD

**Issue by MrEveryDay98** [blawar/ooot#37] opened 2022-02-01 22:41 UTC
![image](https://user-images.githubusercontent.com/98854338/152063720-823827e5-b1eb-48f7-88cd-ffb3e741d7df.png)

**Comment by blawar** [comment] 2022-02-04 00:47
This is caused by frame buffer emulation not being enabled.  Keeping this open until FBE is implemented.

**Comment by Zero3K** [comment] 2022-02-04 17:16
I think this is a duplicate of #7.

**Comment by Zero3K** [comment] 2022-02-09 02:16
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.

**Closed by Zero3K** 2022-02-09 02:16 UTC
Labels: frame buffer emulation
