### ISSUE TITLE
Kakariko graveyard has unexpected enemies as adult

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#110] opened 2022-02-11 03:04 UTC
## Current Behavior
As an adult, the graveyard has several keese and skullwalltulas that aren't there in retail, or even the debug rom.
Time of day does not seem to matter. The enemies are not present as a child.

## Expected Behavior
No keese or skullwalltulas in the graveyard.

## Steps to Reproduce

Start a game in the first slot, select adult Link and go to the graveyard (3rd option)

https://user-images.githubusercontent.com/88684291/153531620-d155ec90-bf1e-4309-9762-d5e262272b77.mp4

**Comment by DaMarkov** [comment] 2022-02-11 03:29
Relevant scene is `spot02_room_1Commands` and `spot02_room_1Set_000490`.
I assume `spot02_room_1ActorList_000078` and `spot02_room_1ActorList_0004EC` got extracted incorrectly.

**Comment by mrneo240** [comment] 2022-02-11 03:48
I dont believe this issue appears with 64bit ZAPD, could not reproduce.

**Comment by Wesley107772** [comment] 2022-02-11 05:02
Updated my build, the 64bit binary should be working fine as the hookshot and the water currents work properly now, but this still happens for me

**Comment by Wesley107772** [comment] 2022-02-11 05:14
Here's another video showing this happen
https://user-images.githubusercontent.com/88684291/153540864-0f6abf80-6c20-4175-b81e-b3d3edfe7f37.mp4

**Comment by DaMarkov** [comment] 2022-02-11 11:10
I can also reproduce this. I have pulled from master, re-extracted the assets and rebuild.

**Comment by GhostlyDark** [comment] 2022-02-15 10:16
For what it's worth, the Adult scene has unused actors which consist of Keese and Skullwultulas. The scene isn't supposed to load them, hence unused.

**Comment by DaMarkov** [comment] 2022-02-20 17:05
Since this issue is a bit older - the bug is still present in Master Quest Debug

**Comment by DaMarkov** [comment] 2022-03-05 23:31
A PR for the has been prepared and will be submitted soon.

**Comment by DaMarkov** [comment] 2022-03-25 23:52
Should be fixed in PR #219

**Closed** 2022-03-31 21:53 UTC
Labels: Debug ROM
