### ISSUE TITLE
Spirit Temple Top Light Mirror not Working

### ISSUE THREAD

**Issue by Chadlight** [blawar/ooot#304] opened 2022-04-23 17:12 UTC
The top mirror in Spirit Temple that allows Link to break the face of the statue to lead to the boss room doesn't work

## Current Behavior
No light reflection from the top mirror, at any FPS 

## Expected Behavior
The top mirror should reflect light after redirecting the mirrors 

## Possible Solution
No idea

## Steps to Reproduce
Go to the end of Spirit Temple at the highest floor and redirect the mirrors to the final mirror

**Comment by blawar** [comment] 2022-05-14 01:45
Are you still able to reproduce this?  I was not able to reproduce, I made it here:

![image](https://user-images.githubusercontent.com/10227949/168406301-ab406c6d-3927-4aab-80ec-c5bbd90e1166.png)

**Comment by Lehpumeh** [comment] 2022-05-14 02:19
The problem happens when you move the final mirror towards the angled mirror to shine at the suns in 60FPS.

20FPS works fine, but you have to move the mirror off and then back on after switching FPS.

https://user-images.githubusercontent.com/99471756/168407174-39eee63c-1b88-4d64-9e62-2791a86a80c5.mp4

**Comment by blawar** [comment] 2022-05-14 13:13
> The problem happens when you move the final mirror towards the angled mirror to shine at the suns in 60FPS.
> 
> 20FPS works fine, but you have to move the mirror off and then back on after switching FPS.
> 
>  SpiritTempleMirror.mp4

Thx, that helped a lot to isolate the issue.  should be fixed in dev.

**Closed by blawar** 2022-05-14 13:13 UTC
