### ISSUE TITLE
Game Crashes During Credits

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#20] opened 2022-02-01 07:27 UTC
[process exited with code 3221225477]

**Comment by mzxrules** [comment] 2022-02-01 15:41
likely related to this line: 
https://github.com/blawar/ooot/blob/master/src/code/z_play.c#L373

**Comment by DaMarkov** [comment] 2022-02-05 01:33
This should be fixed as soon as PR #49 is merged.

**Comment by Zero3K** [comment] 2022-02-06 18:56
Please retest since #49 was merged.

**Comment by blawar** [comment] 2022-02-07 00:00
Unable to reproduce with master, presumed fixed.  Please re-open if the issue persists.

**Closed by blawar** 2022-02-07 00:00 UTC
