### ISSUE TITLE
Sound of navi & holding Z pitched incorrectly

### ISSUE THREAD

**Issue by nitrostemp** [blawar/ooot#320] opened 2022-05-14 11:47 UTC
## Current Behavior
Sounds are incorrectly pitch

## Expected Behavior
both navi and holding z sounds need to be deeper

**Comment by frizzle101101** [comment] 2022-09-08 09:25
Ive almost gotten so used to this I kinda forgot about these, list any other ones you find in this issue

**Comment by frizzle101101** [comment] 2022-09-08 10:09
duplicate of #222

**Closed by frizzle101101** 2022-09-08 10:09 UTC
