### ISSUE TITLE
Some Action Icon Text Missing

### ISSUE THREAD

**Issue by Dewey-Wilkerson** [blawar/ooot#143] opened 2022-02-13 08:46 UTC
## Current Behavior
The text on the action icon does not appear for some actions

## Expected Behavior
A button icon should read "Attack" and "Read"

![Base Profile Screenshot 2022 02 13 - 03 27 22 61](https://user-images.githubusercontent.com/17395556/153745764-b551fc49-3adb-48ba-8add-9cf8e5bd1939.png)
![Base Profile Screenshot 2022 02 13 - 03 24 46 43](https://user-images.githubusercontent.com/17395556/153745772-62bab7ab-6e7e-4965-a7f2-bc0571105b21.png)

**Comment by Daniel6372** [comment] 2022-02-13 21:11
Duplicate of #119

**Comment by DaMarkov** [comment] 2022-02-20 15:51
Fixed in PR #175

**Closed** 2022-02-20 17:15 UTC
