### ISSUE TITLE
Fishing rod visual bug

### ISSUE THREAD

**Issue by ungaDamage** [blawar/ooot#42] opened 2022-02-02 02:33 UTC
Upon getting the fishing rod, young link sports an interesting cape. Haven't tested adult.
![fishing rod visual bug](https://user-images.githubusercontent.com/98857629/152082132-03628fe1-aace-4652-b911-749909f309fc.PNG)

**Comment by Zero3K** [comment] 2022-02-08 19:20
That looks like an issue caused by no frame buffer emulation being used (which will be used soon).

**Comment by DaMarkov** [comment] 2022-02-08 21:23
I am sure if this is due to FBE, but it's at least fixed for me (with FBE enabled).
Should be considered fixed when the FBE PR is merged.
![image](https://user-images.githubusercontent.com/35939509/153077772-e7a1459e-a21a-4c28-8432-045235e9627a.png)

**Comment by Zero3K** [comment] 2022-02-09 02:12
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.

**Closed by Zero3K** 2022-02-09 02:12 UTC
Labels: frame buffer emulation
