### ISSUE TITLE
Link will sink to the ground when holdring right+Z

### ISSUE THREAD

**Issue by topkeksphagetti** [blawar/ooot#28] opened 2022-02-01 16:31 UTC
![image](https://user-images.githubusercontent.com/15426253/152009552-3c4f4b0e-49a0-4bbf-8b6b-098659b26b63.png)

**Comment by Zero3K** [comment] 2022-02-06 18:57
This is a duplicate of #13.

**Closed** 2022-02-06 18:58 UTC
