### ISSUE TITLE
Softlock after completing Water Temple - Sheik cutscene

### ISSUE THREAD

**Issue by mario8000** [blawar/ooot#210] opened 2022-03-12 04:17 UTC
## Current Behavior

You finish the dialogue with Sheik, she jumps in the water disappears then the game softlocks at a black screen.
![image](https://user-images.githubusercontent.com/24818108/158003303-5dfdaea5-7a01-4e98-9a33-8768870d8357.png)
Break in code at the time of softlock:
![image](https://user-images.githubusercontent.com/24818108/158003309-e245f68e-d7c0-45d7-83fe-8d96e54c4dd2.png)

## Expected Behavior

you finish the cutscene and are able to control link again to shoot the arrow into the morning sun.

## Steps to Reproduce

1. Defeat the water temple boss
2. Finish the cutscenes directly afterwards with Sheik
3. Softlocks at a black screen

**Comment by DaMarkov** [comment] 2022-03-26 19:13
This bug was introduced in a quite recent commit. I am doing a git bisect to isolate which commit is the cause of this bug.

**Comment by DaMarkov** [comment] 2022-03-26 21:24
To reproduce this bug choose Lake Hylia in map select and add
`gSaveContext.cutsceneIndex = 65520;
gSaveContext.sceneSetupIndex = 4;`
in `cmd_alternate_headers` after `osSyncPrintf`

git bisect identified 4cd77f8f1a05add867e5ec49f25c4cf3e2ff6a10 as the faulty commit.

**Comment by DaMarkov** [comment] 2022-03-26 21:55
Fixed in 046589a89f0be2909a11bf79d693e39e7d001875

**Closed by DaMarkov** 2022-03-26 21:55 UTC
Labels: Debug ROM, High Priority
