### ISSUE TITLE
Golden Skulltula Token Icon on Kokiri Forest map

### ISSUE THREAD

**Issue by Detrimantix** [blawar/ooot#54] opened 2022-02-05 19:47 UTC
Golden skulltula Token Icon on Kokiri Forest map is visible without acquiring any golden skulltulas.

![image](https://user-images.githubusercontent.com/99096248/152656735-2aee8842-41fe-4d6a-a968-6da8802cd6bb.png)

**Comment by blawar** [comment] 2022-02-11 00:00
Is this bug still on master?  I am unable to reproduce.

**Comment by Wesley107772** [comment] 2022-02-11 01:10
Seems to be fixed now. Related to this issue was the skulltulas not appearing at all in Kokiri Forest, but now they appear as usual again

**Closed** 2022-02-11 01:16 UTC

**Comment by DaMarkov** [comment] 2022-02-11 02:22
Turns out this "bug" is a feature of the debug version.
This also happens on an emulator. Unfortunately, I couldn't find it anywhere documented.
