### ISSUE TITLE
Jabu-Jabu's Belly PAL 1.0  - Crash when attacking certain creatures with boomerang 

### ISSUE THREAD

**Issue by mario8000** [blawar/ooot#204] opened 2022-03-05 18:41 UTC
## Current Behavior

Game crashes when attacking a specific creature in Jabu Jabu's Belly with the boomerang
## Expected Behavior

Dies, no crash in gameplay

## Possible Solution

Seems to happen when the boomerang makes impact with a specific creature, will upload a picture. idk the name of the monster. However, they are in the tunnel in the ground directly after obtaining the boomerang.

![oot crash1](https://user-images.githubusercontent.com/24818108/156896117-de54a731-aaca-4931-868e-cae6284a8e6c.png)

## Steps to Reproduce

1.go to jabu jabu belly
2. get the boomerang
3. attack some of the monsters directly outside the boomerang room with the boomerang
4. crash

**Comment by DaMarkov** [comment] 2022-03-05 21:16
I could only reproduce this crash once in about 30m of playtime.
I couldnt really debug in since optimizations in gliden were enabled.
Infinite "loop" in `RSP_ProcessDList ` when calling `_ProcessDList`.
Couldn't get more information, I assume `while (!RSP.halt)` is the infinite loop.

**Comment by DaMarkov** [comment] 2022-03-05 22:22
This happens almost every time when using a deku nut.
Fix is in PR #206. Another possible fix has been added to GlideN64 as a PR.

**Closed** 2022-03-06 15:05 UTC
Labels: Retail ROM
