### ISSUE TITLE
Crash in title screen

### ISSUE THREAD

**Issue by Vulto** [blawar/ooot#97] opened 2022-02-09 17:06 UTC
The game crash as soon as you open the title screen if you press start repeteadly at launch

## Steps to Reproduce

1. Open the game and press start repeteadly it will seg fault

**Comment by GreenSwede** [comment] 2022-02-09 19:04
I was unable to reproduce this on Windows 10 (commit 48d8b50ce45c153faa2b19abe88629b754cbbcac). Are you on Linux?

Pressing start repeatedly is meant to start the demo sequences, and they play fine for me. My only issue is that the Light Temple demo is interactive instead of being a demo, so I was able to progress and spawn as Adult Link

https://user-images.githubusercontent.com/42186507/153271832-f414f3e0-3217-4e5b-84f0-dcdc9fb5dcdb.mp4

**Comment by mrneo240** [comment] 2022-02-09 19:28
good to know that happens to someone else....

**Comment by Vulto** [comment] 2022-02-09 20:03
> good to know that happens to someone else....

You mean the crash ?

**Comment by mrneo240** [comment] 2022-02-09 20:18
> > good to know that happens to someone else....
> 
> You mean the crash ?

the playability of that particular demo, as shown in the video

**Comment by DaMarkov** [comment] 2022-02-09 21:08
I can sometimes reproduce it (depends how fast I press).

When it crashes
`Gameplay_InitScene()` is called with `spawn = 0`
In `cmd_alternate_headers()`  `gSaveContext.sceneSetupIndex` is 10,
In `altHeader = ((SceneCmd**)SEGMENTED_TO_VIRTUAL(cmd->altHeaders.segment))[gSaveContext.sceneSetupIndex - 1];`
`altHeader` gets set to 0x0000ffff,
`Scene_ExecuteCommands` get called,
crashes on `cmdCode = sceneCmd->base.code;`

Is this just an invalid scene?
`sceneSegment` point to `spot18_sceneCommands` by the way

**Comment by mrneo240** [comment] 2022-02-09 21:14
Great reporting. 👍

**Comment by DaMarkov** [comment] 2022-03-05 01:48
This should be fixed with PR #203.
Can anyone try to recreated this issue after the PR got merged?

**Closed** 2022-03-06 15:08 UTC
Labels: Debug ROM
