### ISSUE TITLE
Obtaining new items show incorrect graphics

### ISSUE THREAD

**Issue by topkeksphagetti** [blawar/ooot#33] opened 2022-02-01 19:15 UTC
![image](https://user-images.githubusercontent.com/15426253/152035454-4efd426f-c36a-4cae-bbd7-3028c124d97f.png)

**Comment by Dewey-Wilkerson** [comment] 2022-02-08 00:58
This might be a one-off bug, or a bug that requires specific steps to reproduce (or was fixed in a prior commit between this bug report and my testing for it).  This prompt works fine for me.

![Base Profile Screenshot 2022 02 07 - 04 56 10 63](https://user-images.githubusercontent.com/17395556/152897748-95bf1f40-f8de-469d-8f92-9c76bae92f1b.png)

**Comment by Zero3K** [comment] 2022-02-08 01:30
It was fixed because of the message fix (I think).

**Closed** 2022-02-08 19:19 UTC
