### ISSUE TITLE
Crash jumping into hole in Bottom of the Well

### ISSUE THREAD

**Issue by minkbob** [blawar/ooot#44] opened 2022-02-02 06:09 UTC
I jumped down the hole that goes to the lower level of Bottom of the Well, and the game threw an exception in the EnGoroiwa_TeleportToWaypoint function in z_en_goroiwa.c.

Exception thrown: read access violation.
**pointPos** was 0x7800D0
![oot_crash](https://user-images.githubusercontent.com/1123342/152101876-d5dd12ac-1a3f-4fc3-a532-4f3d8d8076f3.png)
.

**Comment by blawar** [comment] 2022-02-05 01:44
I was unable to reproduce, do I have to jump down during a certain time of day or something? Is the issue still present on master?

**Comment by DaMarkov** [comment] 2022-02-06 14:51
Since the crash happens in `EnGoroiwa_TeleportToWaypoint()` I assume this is the same issue as in #40 #50 and #62.
We should have a label for all these path list bugs.

**Comment by mrneo240** [comment] 2022-02-06 16:27
I believe should be fixed after pulling this and extracting assets again. Also 100% fixes #40 and likely #50 and #62 
mrneo240/ooot-lite@52c72abe513c89d923d62f6178e7381a4dd9f198

**Closed** 2022-02-09 15:10 UTC
